### ISSUE TITLE
pdf created but completely empty

### ISSUE THREAD

**Issue by benlutz** [ch99q/nuxt-pdf#7] opened 2020-08-03 13:19 UTC
Hi,
I just stumbled upon your plugin and it was exactly what I was looking for. Unfortunately, the generated .pdf is completely empty. I am using @nuxt/content for product pages and then want to use nuxt-pdf to generate a companion pdf of the same page. What could be a good reason, why the generated pdf ist completely empty?

Thanks!

**Comment by AdrianoCahete** [comment] 2020-08-10 07:39
Same here, but just when I add more content/components.

My bet is that the pdf task runs before the page rendering is complete, so it gets nothing.

**Comment by AdrianoCahete** [comment] 2020-08-11 18:03
The problem seems to be in the [pdf.css](https://github.com/ch99q/nuxt-pdf/blob/36bb8db6a3eb699c21319a13b1b934a65543d4f0/lib/css/pdf.css#L6) file: 
https://github.com/ch99q/nuxt-pdf/blob/36bb8db6a3eb699c21319a13b1b934a65543d4f0/lib/css/pdf.css#L6

This file has a `@media print` that makes everything invisible, but add a `page` class with visible after. The problem is that not everyone uses the default `page` class, like in my case.

The workaround here is to add a media print with `visibility: visible !important `in your code:

```
@media print {
  body {
    visibility: visible !important;
  }
}
```

**!important** *is needed to overwrite the pdf file since I really don't know the order of the styles in the rendered file.*

I create this file in my css folder root and called that in the layout file that I need, after all the base stylesheets that I have.

**Comment by benlutz** [comment] 2020-08-11 19:30
Thank you for your suggestion, @AdrianoCahete! I will try to implement your workaround. Should this thread be labelled as a bug now?

**Comment by AdrianoCahete** [comment] 2020-08-12 01:10
I think so. I don't know if you can add this label or if we need to wait for @ch99q

**Comment by ch99q** [comment] 2020-08-12 06:01
I Will look into it, sorry for the inactivity on my side.

I will take a look at the module today ☺️

**Comment by benlutz** [comment] 2020-08-12 07:52
@ch99q no worries! Great module-idea though! Looking forward to its development

**Comment by ch99q** [comment] 2020-08-12 09:35
Just finishing it off, got it working in build and dev mode too, so it works without generating too.

Some small breaking changes, but for a module that doesn't work, I think it's gonna be fine. 😅

**Comment by ch99q** [comment] 2020-08-12 11:19
I realized it was intended, but I forgot to describe it in the readme. That's fixed now with additional support for `nuxt build` and `nuxt dev`.

There are some small breaking changes, you will need to change from:
```js
// nuxt.config.js

pdf: {
  // ...,
  routes: [
    {
      filename: "documentation-vue.pdf",
      directory: "downloads",
      route: "docs/vue",
    }
  ]
}
```

to:

```js
// nuxt.config.js

pdf: {
  // ...,
  routes: [
    {
      file: "downloads/documentation-vue.pdf",
      route: "docs/vue",
    }
  ]
}
```

**Closed by ch99q** 2020-08-12 11:19 UTC
Labels: documentation

**Comment by AdrianoCahete** [comment] 2020-08-12 21:36
> but for a module that doesn't work

But works! With a few workarounds, but works.... hahaha

Thanks for all the fixes and the library!
